services:
  _defaults:
    autowire: true
    autoconfigure: true

  Dantweb\EcwServer\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'