name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create directory structure
        run: |
          mkdir -p app/web
          # Move specific files/directories instead of the entire directory
          find . -maxdepth 1 -not -path "./app" -not -path "." | xargs -I {} mv {} app/web/


      - name: Clone loopai-core
        run: git clone -b production https://github.com/dantweb/ecwatch-core.git app/web/core

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'


      - name: Install dependencies for loopai-core
        working-directory: app/web/core
        run: composer install

      - name: Install dependencies for ecw-server
        working-directory: app/web
        run: |
          composer install

      - name: Run tests
        working-directory: app/web
        run: |
          composer test
