name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: [ "mbstring", "intl" ]
          ini-values: |
            post_max_size=256M
            upload_max_filesize=256M

      - name: Clone ecwatch-web Repository
        run: |
          # Replace the URL below with the actual repository URL for ecwatch-web
          git clone https://example.com/ecwatch-web.git

      - name: Clone core into app/core
        run: |
          mkdir -p app
          # Replace the URL below with the actual repository URL for core
          git clone https://example.com/core.git app/core

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Static Code Analysis
        run: composer check

      - name: Run PHPUnit Tests
        run: composer test
