name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: json
          coverage: none

      - name: Clone loopai-core
        run: |
          git clone --branch production --depth 1 https://github.com/dantweb/loopai-core.git core

      - name: Install main project dependencies
        run: composer install --no-progress --no-suggest

      - name: Install loopai-core dependencies
        working-directory: ./core
        run: composer install --no-progress --no-suggest

      - name: Run tests
        run: composer test
