name: CI

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: |
          git clone --branch production --depth 1 https://github.com/dantweb/ecwatch-core.git core

      - name: Install main project dependencies
        run: composer install --no-progress --no-suggest

      - name: Install loopai-core dependencies
        working-directory: ./core
        run: composer install --no-progress --no-suggest

      - name: Run tests
        run: composer test

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.2]

    env:
      KERNEL_CLASS: 'App\\Kernel'
      APP_SECRET: '$ecretf0rt3st'
      SYMFONY_DEPRECATIONS_HELPER: 999999

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run static analysis and tests
        run: |
          composer phpcs
          composer phpstan
          composer phpmd
          composer test
     
