name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Clone ecwatch-web
        run: |
          git clone https://github.com/your-org/ecwatch-web.git
      - name: Clone core repository into app/core
        run: |
          mkdir -p app/core
          git clone https://github.com/your-org/core.git app/core
      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest
      - name: Run static analysis (PHPCS, PHPStan, PHPMD)
        run: composer check
      - name: Run PHPUnit tests
        run: composer test
