name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
          tools: composer:v2

      - name: Clone loopai-core
        run: |
          mkdir -p /app/web/core
          git clone -b production https://github.com/dantweb/loopai-core.git /app/web/core

      - name: Install dependencies
        run: |
          composer install --working-dir=/app/web
          composer update --working-dir=/app/web/core

      - name: Run tests
        run: composer test --working-dir=/app/web